const ATTEMPTS_LIMIT = 50;
const ATTEMPT_DELAY = 100;
const DEFAULT_LANGUAGE = 'pl';
const CUSTOM_POSTFIX = '-custom';
const BASIC_TAG = 'div';

export {
  ATTEMPTS_LIMIT,
  ATTEMPT_DELAY,
  DEFAULT_LANGUAGE,
  CUSTOM_POSTFIX,
  BASIC_TAG,
};
